const imgFolder = "/assets/img/emojis/"

export enum contentSrc{
    Thermos = imgFolder + 'thermos.png',
    PocketKnife = "🔪",
    Compass = imgFolder + 'compass.png',
    WarmGloves = '🧤',
    Guidebook = '📔',
    ScentedCandle = '🕯',
    SoftBlanket = imgFolder + 'blanket.png',
    Mugs = '☕',
    Journal = '📓',
    FieldGuide = '📖',
    HarvestTool = '👨‍🌾',
    DriedMushrooms =imgFolder + 'mushroom.png',
    HerbTea = '🍵',
    Soap = imgFolder + 'soap.png',
    Pendant = imgFolder + 'pendant.png',
    RuneStoneCoaster = imgFolder + 'rune.png',
    MeadMaker = '🍻',
    Novel = '✍',
    JigsawPuzzle = imgFolder + 'jigsaw.png',
    BathSalt = imgFolder + 'salt.png',
    NordicMyths = imgFolder + 'hammer.png',
    ArtPrint = '🖌',
    FlowerCrown = '🌻',
    BerryTea = '🍒',
    SkinCareProducts = imgFolder + 'skincare.png',
    DanceGuide = '🕺',
    LingonberryPreserve = imgFolder + 'lingonberry.png',
    Crispbread = '🍞',
    SmokedSalmon = '🐟',
    CloudberryJam = imgFolder + 'lingonberry.png',
    ArtisanChocolate = '🍫',
    GeometricPlanter = '🎍',
    WoodenUtensils = '🍴',
}